-- Extend the shared OTR schema for broadcast history and CBSRMT source enrichment.
-- This migration is automatic and safe to run once through scripts/db.py update.

BEGIN;

ALTER TABLE episode
    ADD COLUMN IF NOT EXISTS note text,
    ADD COLUMN IF NOT EXISTS fisher_rubric numeric(6,2),
    ADD COLUMN IF NOT EXISTS fisher_cast_roles text;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'episode_fisher_rubric_range'
    ) THEN
        ALTER TABLE episode
            ADD CONSTRAINT episode_fisher_rubric_range
            CHECK (fisher_rubric IS NULL OR (fisher_rubric >= 0 AND fisher_rubric <= 100));
    END IF;
END
$$;

CREATE TABLE IF NOT EXISTS broadcast (
    broadcast_id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    series_id            bigint NOT NULL REFERENCES series(series_id) ON DELETE CASCADE,
    episode_id           bigint REFERENCES episode(episode_id) ON DELETE SET NULL,
    sequence_number      integer,
    air_date             date NOT NULL,
    title                text,
    note                 text,
    broadcast_type       text NOT NULL CHECK (
        broadcast_type IN ('original', 'repeat', 'no_episode', 'other')
    ),
    legacy_system        text,
    legacy_broadcast_id  bigint,
    created_at           timestamptz NOT NULL DEFAULT now(),
    updated_at           timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT broadcast_legacy_identity
        UNIQUE NULLS NOT DISTINCT (legacy_system, legacy_broadcast_id)
);

CREATE INDEX IF NOT EXISTS idx_broadcast_series_date
    ON broadcast(series_id, air_date);

CREATE INDEX IF NOT EXISTS idx_broadcast_episode
    ON broadcast(episode_id);

CREATE TABLE IF NOT EXISTS genre (
    genre_id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug                 text NOT NULL UNIQUE,
    name                 text NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS episode_genre (
    episode_id           bigint NOT NULL REFERENCES episode(episode_id) ON DELETE CASCADE,
    genre_id             bigint NOT NULL REFERENCES genre(genre_id) ON DELETE RESTRICT,
    legacy_system        text,
    legacy_record_id     bigint,
    PRIMARY KEY (episode_id, genre_id),
    CONSTRAINT episode_genre_legacy_identity
        UNIQUE NULLS NOT DISTINCT (legacy_system, legacy_record_id)
);

CREATE TABLE IF NOT EXISTS legacy_episode_adaptation (
    legacy_episode_adaptation_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    episode_id                   bigint NOT NULL REFERENCES episode(episode_id) ON DELETE CASCADE,
    legacy_system                text NOT NULL,
    legacy_record_id             bigint NOT NULL,
    legacy_adaptation_id         bigint NOT NULL,
    CONSTRAINT legacy_episode_adaptation_source_key
        UNIQUE (legacy_system, legacy_record_id),
    CONSTRAINT legacy_episode_adaptation_value_key
        UNIQUE (legacy_system, episode_id, legacy_adaptation_id)
);

CREATE TABLE IF NOT EXISTS import_issue (
    import_issue_id      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_system        text NOT NULL,
    issue_type           text NOT NULL,
    legacy_episode_id    bigint,
    legacy_person_id     bigint,
    details              jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at           timestamptz NOT NULL DEFAULT now(),
    resolved_at          timestamptz
);

CREATE INDEX IF NOT EXISTS idx_import_issue_open
    ON import_issue(source_system, issue_type)
    WHERE resolved_at IS NULL;

COMMIT;
