-- OTR Catalog shared relational schema
-- PostgreSQL 15+
-- One database for all radio series; people are global and episodes belong to a series.

BEGIN;

CREATE TABLE IF NOT EXISTS series (
    series_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug text NOT NULL UNIQUE,
    name text NOT NULL,
    network text,
    start_date date,
    end_date date,
    description text,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS series_run (
    series_run_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    series_id bigint NOT NULL REFERENCES series(series_id) ON DELETE CASCADE,
    run_name text,
    network text,
    sponsor text,
    format text,
    start_date date,
    end_date date,
    notes text
);

CREATE TABLE IF NOT EXISTS person (
    person_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug text UNIQUE,
    first_name text,
    middle_name text,
    last_name text,
    display_name text NOT NULL,
    bio text,
    birth_date date,
    death_date date,
    imdb_url text,
    legacy_system text,
    legacy_person_id bigint,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT person_legacy_identity UNIQUE NULLS NOT DISTINCT (legacy_system, legacy_person_id)
);

CREATE INDEX IF NOT EXISTS idx_person_name ON person (last_name, first_name, middle_name);

CREATE TABLE IF NOT EXISTS person_alias (
    person_alias_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_id bigint NOT NULL REFERENCES person(person_id) ON DELETE CASCADE,
    alias_name text NOT NULL,
    alias_type text NOT NULL DEFAULT 'alternate_name',
    source_note text,
    UNIQUE(person_id, alias_name, alias_type)
);

CREATE TABLE IF NOT EXISTS episode (
    episode_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    series_id bigint NOT NULL REFERENCES series(series_id) ON DELETE CASCADE,
    series_run_id bigint REFERENCES series_run(series_run_id) ON DELETE SET NULL,
    series_episode_number text,
    air_date date,
    title text,
    description text,
    broadcast_status text,
    preservation_status text,
    feature_type text,
    legacy_system text,
    legacy_episode_id bigint,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT episode_legacy_identity UNIQUE NULLS NOT DISTINCT (legacy_system, legacy_episode_id)
);

CREATE INDEX IF NOT EXISTS idx_episode_series_date ON episode(series_id, air_date);
CREATE INDEX IF NOT EXISTS idx_episode_series_number ON episode(series_id, series_episode_number);

CREATE TABLE IF NOT EXISTS credit_type (
    credit_type text PRIMARY KEY,
    display_name text NOT NULL,
    is_performance boolean NOT NULL DEFAULT false
);

INSERT INTO credit_type(credit_type, display_name, is_performance) VALUES
    ('actor','Actor',true),
    ('writer','Writer',false),
    ('adapter','Adapter',false),
    ('director','Director',false),
    ('producer','Producer',false),
    ('announcer','Announcer',true),
    ('narrator','Narrator',true),
    ('host','Host',true),
    ('composer','Composer',false),
    ('sound_effects','Sound Effects',false)
ON CONFLICT (credit_type) DO NOTHING;

CREATE TABLE IF NOT EXISTS episode_credit (
    episode_credit_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    episode_id bigint NOT NULL REFERENCES episode(episode_id) ON DELETE CASCADE,
    person_id bigint NOT NULL REFERENCES person(person_id) ON DELETE RESTRICT,
    credit_type text NOT NULL REFERENCES credit_type(credit_type),
    billing_order integer,
    notes text,
    legacy_system text,
    legacy_credit_id bigint,
    CONSTRAINT episode_credit_legacy_identity UNIQUE NULLS NOT DISTINCT (legacy_system, legacy_credit_id),
    CONSTRAINT episode_credit_unique UNIQUE NULLS NOT DISTINCT (episode_id, person_id, credit_type, billing_order)
);

CREATE INDEX IF NOT EXISTS idx_episode_credit_person ON episode_credit(person_id, credit_type);
CREATE INDEX IF NOT EXISTS idx_episode_credit_episode ON episode_credit(episode_id, credit_type);

CREATE TABLE IF NOT EXISTS performance_role (
    performance_role_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    episode_credit_id bigint NOT NULL REFERENCES episode_credit(episode_credit_id) ON DELETE CASCADE,
    character_name text NOT NULL,
    role_order integer,
    notes text,
    UNIQUE NULLS NOT DISTINCT (episode_credit_id, character_name, role_order)
);

CREATE TABLE IF NOT EXISTS episode_relationship (
    episode_relationship_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    episode_id bigint NOT NULL REFERENCES episode(episode_id) ON DELETE CASCADE,
    related_episode_id bigint NOT NULL REFERENCES episode(episode_id) ON DELETE CASCADE,
    relationship_type text NOT NULL CHECK (relationship_type IN ('repeat_of','rebroadcast_of','remake_of','continuation_of','adaptation_of')),
    notes text,
    UNIQUE(episode_id, related_episode_id, relationship_type),
    CHECK (episode_id <> related_episode_id)
);

CREATE TABLE IF NOT EXISTS source (
    source_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_type text,
    title text,
    url text,
    citation text,
    notes text
);

CREATE TABLE IF NOT EXISTS entity_source (
    entity_source_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_id bigint NOT NULL REFERENCES source(source_id) ON DELETE CASCADE,
    entity_type text NOT NULL CHECK (entity_type IN ('series','episode','person','episode_credit')),
    entity_id bigint NOT NULL,
    source_role text,
    confidence text CHECK (confidence IS NULL OR confidence IN ('high','medium','low')),
    notes text,
    UNIQUE(source_id, entity_type, entity_id, source_role)
);

COMMIT;
